networks:
  db_network:
    driver: bridge
  api_network:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
  api:
    build: backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - db_network
      - api_network
  web:
    build: frontend
    restart: unless-stopped
    ports:
      - "44144:80"
    depends_on:
      - api
    environment:
      API_HOST: api
    networks:
      - api_network
