networks:
  db_network:
    driver: bridge
  api_network:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
  api:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - db_network
  web:
    build: frontend
    restart: always
    ports:
      - "44144:80"
    depends_on:
      - api
    networks:
      - api_network
