FROM debian:latest

WORKDIR /app

RUN apt update && apt install -y elixir && rm -rf /var/lib/apt/lists/*
RUN mix local.hex --force

#CMD [ "mix", "deps.get", "&&", "mix", "phx.server" ]
CMD [ "mix", "phx.server" ]
EXPOSE 4000
