apiVersion: v1
kind: Secret
metadata:
  name: web-login-demo-secret
type: Opaque
data:
  DATABASE_URL: ZWN0bzovL2RlZmF1bHQ6YWJjQGRiL3dlYl9sb2dpbl9kZW1vX2Rldgo=
  SECRET_KEY_BASE: OVk3YVNJKzVDVEpiQXpyQmFISms0NnZFNnRxQWl4T3NKMWJUZkduKzYrbThFU3RDejZJcHlBMEtWdmV2L2lCTA==
